### ISSUE TITLE
A `basedmypy` key in config files for basedmypy exclusive configuration options

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#158]
So that mypy and based mypy can coexist

```toml
[tool.mypy]
sus_sus = true

[tool.basedmypy]
amongus = true
```
```ini
[mypy]
sus_sus = true

[basedmypy]
amongus = true
```
