### ISSUE TITLE
infer property types treats the setter as an unchecked function

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#350]
### Gist to reproduce

```python
class A:
    @property
    def foo(self) -> int:
        ...

    @foo.setter
    def foo(self, value):
        reveal_type(value) # reveal_type' always outputs 'Any' in unchecked functions
```

### Basedmypy version

1.4.0

### Configuration options from `pyproject.toml` (and other config files)

```toml
[tool.mypy]
check_untyped_defs = false
```
### Python version used

3.10

### Operating system and version

windows 10

**Comment by KotlinIsland** [comment]
What options do you have set? I'm not seeing this error.

**Comment by DetachHead** [comment]
soz i assumed it was the defaults causing it
```toml
[tool.mypy]
check_untyped_defs = false
```
