### ISSUE TITLE
config options for evaluated types

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#637]
Pydantic et al evaluate types, and would be incompatable with a lot of based types, so:
```toml
[tool.mypy]
evaluated_type_bases = ["pydantic.BaseModel"]
evaluated_type_decorators = ["pydantic.dataclasses.dataclass"]
```
